# Generated by Django 5.0 on 2025-12-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notarstellen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Deaktivierte Einträge bleiben erhalten, werden aber nicht mehr verwendet', verbose_name='Ist aktiv')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('titel', models.CharField(blank=True, help_text='z.B. "Dr.", "Prof. Dr."', max_length=50, verbose_name='Titel')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('beginn_datum', models.DateField(help_text='Beginn der Tätigkeit', verbose_name='Beginn')),
                ('ende_datum', models.DateField(blank=True, help_text='Ende der Tätigkeit (falls beendet)', null=True, verbose_name='Ende')),
                ('notar_id', models.CharField(help_text='Eindeutige Identifikationsnummer des Notars', max_length=50, unique=True, verbose_name='Notar-ID')),
                ('bestellt_am', models.DateField(help_text='Datum der Bestellung zum Notar', verbose_name='Bestellt am')),
                ('war_vorher_anwaerter', models.BooleanField(default=False, help_text='Hat die Person vorher als Notar-Anwärter gearbeitet?', verbose_name='War vorher Notar-Anwärter')),
                ('notiz', models.TextField(blank=True, help_text='Interne Notizen und Bemerkungen', verbose_name='Notizen')),
                ('notarstelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notare', to='notarstellen.notarstelle', verbose_name='Notarstelle')),
            ],
            options={
                'verbose_name': 'Notar',
                'verbose_name_plural': 'Notare',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='NotarAnwaerter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Deaktivierte Einträge bleiben erhalten, werden aber nicht mehr verwendet', verbose_name='Ist aktiv')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('titel', models.CharField(blank=True, help_text='z.B. "Dr.", "Prof. Dr."', max_length=50, verbose_name='Titel')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('beginn_datum', models.DateField(help_text='Beginn der Tätigkeit', verbose_name='Beginn')),
                ('ende_datum', models.DateField(blank=True, help_text='Ende der Tätigkeit (falls beendet)', null=True, verbose_name='Ende')),
                ('anwaerter_id', models.CharField(help_text='Eindeutige Identifikationsnummer des Anwärters', max_length=50, unique=True, verbose_name='Anwärter-ID')),
                ('zugelassen_am', models.DateField(help_text='Datum der Zulassung als Notar-Anwärter', verbose_name='Zugelassen am')),
                ('geplante_bestellung', models.DateField(blank=True, help_text='Geplantes Datum für Bestellung zum Notar', null=True, verbose_name='Geplante Bestellung')),
                ('notiz', models.TextField(blank=True, help_text='Interne Notizen und Bemerkungen', verbose_name='Notizen')),
                ('betreuender_notar', models.ForeignKey(help_text='Der Notar, bei dem der Anwärter lernt', on_delete=django.db.models.deletion.PROTECT, related_name='betreute_anwaerter', to='personen.notar', verbose_name='Betreuender Notar')),
                ('notarstelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anwaerter', to='notarstellen.notarstelle', verbose_name='Notarstelle')),
            ],
            options={
                'verbose_name': 'Notar-Anwärter',
                'verbose_name_plural': 'Notar-Anwärter',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.AddIndex(
            model_name='notar',
            index=models.Index(fields=['notar_id'], name='personen_no_notar_i_a60960_idx'),
        ),
        migrations.AddIndex(
            model_name='notar',
            index=models.Index(fields=['notarstelle', 'ist_aktiv'], name='personen_no_notarst_c7e91e_idx'),
        ),
        migrations.AddIndex(
            model_name='notar',
            index=models.Index(fields=['nachname', 'vorname'], name='personen_no_nachnam_68b87d_idx'),
        ),
        migrations.AddIndex(
            model_name='notaranwaerter',
            index=models.Index(fields=['anwaerter_id'], name='personen_no_anwaert_885b27_idx'),
        ),
        migrations.AddIndex(
            model_name='notaranwaerter',
            index=models.Index(fields=['betreuender_notar', 'ist_aktiv'], name='personen_no_betreue_c72025_idx'),
        ),
        migrations.AddIndex(
            model_name='notaranwaerter',
            index=models.Index(fields=['notarstelle', 'ist_aktiv'], name='personen_no_notarst_dc3ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='notaranwaerter',
            index=models.Index(fields=['nachname', 'vorname'], name='personen_no_nachnam_68be6c_idx'),
        ),
    ]
