# Generated by Django 5.2.9 on 2025-12-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaranwaerter',
            options={'ordering': ['nachname', 'vorname'], 'verbose_name': 'Notariatskandidat', 'verbose_name_plural': 'Notariatskandidaten'},
        ),
        migrations.AlterField(
            model_name='notar',
            name='war_vorher_anwaerter',
            field=models.BooleanField(default=False, help_text='Hat die Person vorher als Notariatskandidat gearbeitet?', verbose_name='War vorher Notariatskandidat'),
        ),
        migrations.AlterField(
            model_name='notaranwaerter',
            name='anwaerter_id',
            field=models.CharField(help_text='Eindeutige Identifikationsnummer des Kandidaten', max_length=50, unique=True, verbose_name='Kandidaten-ID'),
        ),
        migrations.AlterField(
            model_name='notaranwaerter',
            name='betreuender_notar',
            field=models.ForeignKey(help_text='Der Notar, bei dem der Kandidat lernt', on_delete=django.db.models.deletion.PROTECT, related_name='betreute_anwaerter', to='personen.notar', verbose_name='Betreuender Notar'),
        ),
        migrations.AlterField(
            model_name='notaranwaerter',
            name='zugelassen_am',
            field=models.DateField(help_text='Datum der Zulassung als Notariatskandidat', verbose_name='Zugelassen am'),
        ),
    ]
