# Generated by Django 5.2.9 on 2025-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0002_alter_notaranwaerter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notar',
            name='notar_id',
            field=models.CharField(help_text='Format: NOT-000001', max_length=50, unique=True, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='notaranwaerter',
            name='anwaerter_id',
            field=models.CharField(help_text='Format: NKA-000001', max_length=50, unique=True, verbose_name='Bezeichnung'),
        ),
    ]
