# Generated by Django 5.2.9 on 2025-12-20 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personen', '0001_initial'),
        ('workflows', '0008_populate_workflow_instanz_kennung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Deaktivierte Einträge bleiben erhalten, werden aber nicht mehr verwendet', verbose_name='Ist aktiv')),
                ('service_id', models.CharField(help_text='Eindeutige ID im Code (z.B. "stammblatt_pdf_einzeln")', max_length=100, unique=True, verbose_name='Service-ID')),
                ('name', models.CharField(help_text='Benutzerfreundlicher Name', max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(help_text='Was macht dieser Service? Wann nutzt man ihn?', verbose_name='Beschreibung')),
                ('icon', models.CharField(default='tools', max_length=50, verbose_name='Bootstrap Icon')),
                ('button_text', models.CharField(default='Service ausführen', max_length=100, verbose_name='Button-Text')),
                ('button_css_class', models.CharField(default='btn-primary', help_text='z.B. "btn-primary", "btn-success", "btn-warning"', max_length=100, verbose_name='Button CSS-Klasse')),
                ('erforderliche_rolle', models.CharField(blank=True, help_text='Leer = alle; sonst z.B. "sachbearbeiter", "leitung"', max_length=50, verbose_name='Erforderliche Rolle')),
            ],
            options={
                'verbose_name': 'Service-Definition',
                'verbose_name_plural': 'Service-Definitionen',
                'ordering': ['kategorie', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(blank=True, help_text='z.B. "file-earmark-pdf", "envelope", "graph-up"', max_length=50, verbose_name='Bootstrap Icon')),
                ('reihenfolge', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Service-Kategorie',
                'verbose_name_plural': 'Service-Kategorien',
                'ordering': ['reihenfolge', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAusfuehrung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('erfolgreich', models.BooleanField(default=True, verbose_name='Erfolgreich')),
                ('fehlermeldung', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('ergebnis_daten', models.JSONField(blank=True, default=dict, help_text='JSON mit Rückgabewerten (z.B. generierte Datei-ID)', verbose_name='Ergebnis-Daten')),
                ('dauer_sekunden', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Dauer (Sekunden)')),
                ('ausgefuehrt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_ausfuehrungen', to=settings.AUTH_USER_MODEL, verbose_name='Ausgeführt von')),
                ('workflow_instanz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_ausfuehrungen', to='workflows.workflowinstanz', verbose_name='Workflow-Instanz')),
                ('workflow_schritt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_ausfuehrungen', to='workflows.workflowschrittinstanz', verbose_name='Workflow-Schritt')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausfuehrungen', to='services.servicedefinition', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service-Ausführung',
                'verbose_name_plural': 'Service-Ausführungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='servicedefinition',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicekategorie', verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('dokument_typ', models.CharField(choices=[('stammblatt', 'Stammblatt'), ('strafregisterauszug', 'Strafregisterauszug'), ('besetzungsvorschlag', 'Besetzungsvorschlag'), ('gutachten', 'Gutachten'), ('beschluss', 'Beschluss'), ('korrespondenz', 'Korrespondenz'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=50, verbose_name='Dokumenten-Typ')),
                ('datei', models.FileField(upload_to='dokumente/%Y/%m/', verbose_name='Datei')),
                ('dateiname', models.CharField(max_length=255, verbose_name='Originaler Dateiname')),
                ('dateityp', models.CharField(help_text='MIME-Type (z.B. "application/pdf")', max_length=50, verbose_name='Dateityp')),
                ('dateigroesse', models.PositiveIntegerField(verbose_name='Dateigröße (Bytes)')),
                ('tags', models.CharField(blank=True, help_text='Komma-getrennte Tags für Suche', max_length=500, verbose_name='Tags')),
                ('anwaerter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='personen.notaranwaerter', verbose_name='Notar-Anwärter')),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hochgeladene_dokumente', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
                ('notar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='personen.notar', verbose_name='Notar')),
                ('workflow_instanz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='workflows.workflowinstanz', verbose_name='Workflow-Instanz')),
                ('generiert_von_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generierte_dokumente', to='services.serviceausfuehrung', verbose_name='Generiert von Service')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-erstellt_am'],
                'indexes': [models.Index(fields=['workflow_instanz', 'dokument_typ'], name='services_do_workflo_955ad2_idx'), models.Index(fields=['notar', 'dokument_typ'], name='services_do_notar_i_b6436b_idx'), models.Index(fields=['anwaerter', 'dokument_typ'], name='services_do_anwaert_f86fb0_idx')],
            },
        ),
    ]
