# Generated by Django 5.2.9 on 2025-12-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0003_alter_notar_notar_id_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='anwaerter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='personen.notaranwaerter', verbose_name='Notariatskandidat'),
        ),
    ]
