# Generated by Django 5.0 on 2025-12-18 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nummernsequenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('jahr', models.PositiveIntegerField(verbose_name='Jahr')),
                ('praefix', models.CharField(choices=[('BES', 'Bestellung'), ('ZUL', 'Zulassung'), ('AUF', 'Aufsicht'), ('ALL', 'Allgemein')], help_text='Präfix für das Aktenzeichen', max_length=10, verbose_name='Präfix')),
                ('aktuelle_nummer', models.PositiveIntegerField(default=0, help_text='Letzte vergebene laufende Nummer', verbose_name='Aktuelle Nummer')),
            ],
            options={
                'verbose_name': 'Nummernsequenz',
                'verbose_name_plural': 'Nummernsequenzen',
                'ordering': ['-jahr', 'praefix'],
                'indexes': [models.Index(fields=['jahr', 'praefix'], name='aktenzeiche_jahr_67e03e_idx')],
                'unique_together': {('jahr', 'praefix')},
            },
        ),
        migrations.CreateModel(
            name='Aktenzeichen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('vollstaendige_nummer', models.CharField(editable=False, help_text='Vollständiges Aktenzeichen (wird automatisch generiert)', max_length=50, unique=True, verbose_name='Aktenzeichen')),
                ('laufnummer', models.PositiveIntegerField(verbose_name='Laufnummer')),
                ('jahr', models.PositiveIntegerField(verbose_name='Jahr')),
                ('kategorie', models.CharField(choices=[('Bestellung', 'Bestellung'), ('Zulassung', 'Zulassung'), ('Aufsicht', 'Aufsicht'), ('Allgemein', 'Allgemein')], help_text='Kategorie des Vorgangs', max_length=50, verbose_name='Kategorie')),
                ('beschreibung', models.TextField(blank=True, help_text='Kurze Beschreibung des Vorgangs', verbose_name='Beschreibung')),
                ('sequenz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aktenzeichen', to='aktenzeichen.nummernsequenz', verbose_name='Sequenz')),
            ],
            options={
                'verbose_name': 'Aktenzeichen',
                'verbose_name_plural': 'Aktenzeichen',
                'ordering': ['-jahr', '-laufnummer'],
                'indexes': [models.Index(fields=['vollstaendige_nummer'], name='aktenzeiche_vollsta_fe5306_idx'), models.Index(fields=['jahr', 'sequenz'], name='aktenzeiche_jahr_511bd9_idx'), models.Index(fields=['kategorie'], name='aktenzeiche_kategor_55243d_idx')],
            },
        ),
    ]
