# Generated by Django 5.0 on 2025-12-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notarstelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Deaktivierte Einträge bleiben erhalten, werden aber nicht mehr verwendet', verbose_name='Ist aktiv')),
                ('notarnummer', models.CharField(help_text='Eindeutige Nummer der Notarstelle, z.B. "1" oder "HH-1"', max_length=20, unique=True, verbose_name='Notarnummer')),
                ('bezeichnung', models.CharField(help_text='z.B. "NOT-1" oder "Notariat Hamburg I"', max_length=100, verbose_name='Bezeichnung')),
                ('name', models.CharField(help_text='Offizieller Name der Notarstelle', max_length=200, verbose_name='Name')),
                ('strasse', models.CharField(max_length=200, verbose_name='Straße')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('stadt', models.CharField(max_length=100, verbose_name='Stadt')),
                ('bundesland', models.CharField(blank=True, max_length=100, verbose_name='Bundesland')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('besetzt_seit', models.DateField(blank=True, help_text='Datum der letzten Besetzung', null=True, verbose_name='Besetzt seit')),
                ('notiz', models.TextField(blank=True, help_text='Interne Notizen und Bemerkungen', verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Notarstelle',
                'verbose_name_plural': 'Notarstellen',
                'ordering': ['notarnummer'],
                'indexes': [models.Index(fields=['notarnummer'], name='notarstelle_notarnu_04e8a2_idx'), models.Index(fields=['ist_aktiv'], name='notarstelle_ist_akt_8f9d1a_idx'), models.Index(fields=['stadt'], name='notarstelle_stadt_c8c25d_idx')],
            },
        ),
    ]
