# Generated by Django 5.2.9 on 2025-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarstellen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notarstelle',
            options={'ordering': ['bezeichnung'], 'verbose_name': 'Notarstelle', 'verbose_name_plural': 'Notarstellen'},
        ),
        migrations.RemoveIndex(
            model_name='notarstelle',
            name='notarstelle_notarnu_04e8a2_idx',
        ),
        migrations.RemoveField(
            model_name='notarstelle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notarstelle',
            name='notarnummer',
        ),
        migrations.AlterField(
            model_name='notarstelle',
            name='bezeichnung',
            field=models.CharField(help_text='Format: NST-000001', max_length=50, primary_key=True, serialize=False, verbose_name='Bezeichnung'),
        ),
    ]
