# Generated by Django 5.2.9 on 2025-12-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarstellen', '0002_alter_notarstelle_options_and_more'),
        ('sprengel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarstelle',
            name='sprengel',
            field=models.ForeignKey(blank=True, help_text='Zugehöriger Notarsprengel (Gerichtsbezirk)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notarstellen', to='sprengel.sprengel', verbose_name='Sprengel'),
        ),
    ]
