# Generated by Django 5.2.9 on 2025-12-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprengel',
            fields=[
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Deaktivierte Einträge bleiben erhalten, werden aber nicht mehr verwendet', verbose_name='Ist aktiv')),
                ('bezeichnung', models.CharField(help_text='Format: SPR-000001', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Bezeichnung')),
                ('name', models.CharField(help_text='z.B. "Sprengel Wien Innere Stadt"', max_length=200, verbose_name='Name')),
                ('gerichtsbezirk', models.CharField(help_text='Zugehöriger Gerichtsbezirk', max_length=200, verbose_name='Gerichtsbezirk')),
                ('bundesland', models.CharField(choices=[('Wien', 'Wien'), ('Niederösterreich', 'Niederösterreich'), ('Oberösterreich', 'Oberösterreich'), ('Steiermark', 'Steiermark'), ('Kärnten', 'Kärnten'), ('Salzburg', 'Salzburg'), ('Tirol', 'Tirol'), ('Vorarlberg', 'Vorarlberg'), ('Burgenland', 'Burgenland')], max_length=100, verbose_name='Bundesland')),
                ('beschreibung', models.TextField(blank=True, help_text='Zusätzliche Informationen zum Sprengel', verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Sprengel',
                'verbose_name_plural': 'Sprengel',
                'ordering': ['bezeichnung'],
                'indexes': [models.Index(fields=['bundesland'], name='sprengel_sp_bundesl_08a1b7_idx'), models.Index(fields=['ist_aktiv'], name='sprengel_sp_ist_akt_b874fe_idx')],
            },
        ),
    ]
