# Generated by Django 5.0 on 2025-12-18 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSchritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='Name des Schritts', max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, help_text='Was muss in diesem Schritt gemacht werden?', verbose_name='Beschreibung')),
                ('reihenfolge', models.PositiveIntegerField(help_text='Position in der Schritt-Sequenz', verbose_name='Reihenfolge')),
                ('geschaetzte_dauer_tage', models.PositiveIntegerField(blank=True, help_text='Wie lange dauert dieser Schritt üblicherweise?', null=True, verbose_name='Geschätzte Dauer (Tage)')),
                ('standard_zustaendige_rolle', models.CharField(choices=[('sachbearbeiter', 'Sachbearbeiter'), ('leitung', 'Leitung'), ('admin', 'Administrator')], default='sachbearbeiter', help_text='Welche Rolle ist üblicherweise für diesen Schritt zuständig?', max_length=20, verbose_name='Standard-zuständige Rolle')),
                ('ist_optional', models.BooleanField(default=False, help_text='Kann dieser Schritt übersprungen werden?', verbose_name='Ist optional')),
            ],
            options={
                'verbose_name': 'Workflow-Schritt',
                'verbose_name_plural': 'Workflow-Schritte',
                'ordering': ['workflow_typ', 'reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='Name des Workflow-Typs', max_length=200, unique=True, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, help_text='Detaillierte Beschreibung des Workflows', verbose_name='Beschreibung')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Kann dieser Workflow-Typ für neue Instanzen verwendet werden?', verbose_name='Ist aktiv')),
                ('erlaube_parallele_schritte', models.BooleanField(default=False, help_text='Können mehrere Schritte gleichzeitig aktiv sein?', verbose_name='Erlaube parallele Schritte')),
                ('erfordert_sequentielle_abarbeitung', models.BooleanField(default=True, help_text='Müssen Schritte in fester Reihenfolge abgearbeitet werden?', verbose_name='Erfordert sequentielle Abarbeitung')),
            ],
            options={
                'verbose_name': 'Workflow-Typ',
                'verbose_name_plural': 'Workflow-Typen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstanz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='Beschreibender Name für diese Workflow-Instanz', max_length=200, verbose_name='Name')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('aktiv', 'Aktiv'), ('abgeschlossen', 'Abgeschlossen'), ('abgebrochen', 'Abgebrochen')], default='entwurf', max_length=20, verbose_name='Status')),
                ('gestartet_am', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('faellig_am', models.DateField(blank=True, help_text='Bis wann sollte dieser Workflow abgeschlossen sein?', null=True, verbose_name='Fällig am')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('aktenzeichen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow', to='aktenzeichen.aktenzeichen', verbose_name='Aktenzeichen')),
                ('betroffene_person', models.ForeignKey(blank=True, help_text='Notar-Anwärter, der betroffen ist (z.B. bei Bestellungsprozess)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='personen.notaranwaerter', verbose_name='Betroffene Person')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('workflow_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instanzen', to='workflows.workflowtyp', verbose_name='Workflow-Typ')),
            ],
            options={
                'verbose_name': 'Workflow-Instanz',
                'verbose_name_plural': 'Workflow-Instanzen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSchrittInstanz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('ausstehend', 'Ausstehend'), ('in_bearbeitung', 'In Bearbeitung'), ('abgeschlossen', 'Abgeschlossen'), ('uebersprungen', 'Übersprungen'), ('fehlgeschlagen', 'Fehlgeschlagen')], default='ausstehend', max_length=20, verbose_name='Status')),
                ('gestartet_am', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('faellig_am', models.DateField(blank=True, null=True, verbose_name='Fällig am')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('workflow_instanz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritt_instanzen', to='workflows.workflowinstanz', verbose_name='Workflow-Instanz')),
                ('workflow_schritt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instanzen', to='workflows.workflowschritt', verbose_name='Workflow-Schritt')),
                ('zugewiesen_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zugewiesene_schritte', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
            ],
            options={
                'verbose_name': 'Workflow-Schritt-Instanz',
                'verbose_name_plural': 'Workflow-Schritt-Instanzen',
                'ordering': ['workflow_schritt__reihenfolge'],
                'unique_together': {('workflow_instanz', 'workflow_schritt')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowKommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('kommentar', models.TextField(verbose_name='Kommentar')),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_kommentare', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('workflow_instanz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='workflows.workflowinstanz', verbose_name='Workflow-Instanz')),
                ('schritt_instanz', models.ForeignKey(blank=True, help_text='Optional: Bezieht sich der Kommentar auf einen bestimmten Schritt?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='workflows.workflowschrittinstanz', verbose_name='Schritt-Instanz')),
            ],
            options={
                'verbose_name': 'Workflow-Kommentar',
                'verbose_name_plural': 'Workflow-Kommentare',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='workflowschritt',
            name='workflow_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='workflows.workflowtyp', verbose_name='Workflow-Typ'),
        ),
        migrations.CreateModel(
            name='WorkflowSchrittUebergang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('bedingung', models.CharField(blank=True, help_text='Optionale Bedingung für diesen Übergang', max_length=200, verbose_name='Bedingung')),
                ('von_schritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebergaenge_von', to='workflows.workflowschritt', verbose_name='Von Schritt')),
                ('zu_schritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebergaenge_zu', to='workflows.workflowschritt', verbose_name='Zu Schritt')),
            ],
            options={
                'verbose_name': 'Workflow-Schritt-Übergang',
                'verbose_name_plural': 'Workflow-Schritt-Übergänge',
                'unique_together': {('von_schritt', 'zu_schritt')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='workflowschritt',
            unique_together={('workflow_typ', 'reihenfolge')},
        ),
    ]
