# Generated by Django 5.2.9 on 2025-12-19 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('datei', models.FileField(upload_to='workflow_dokumente/%Y/%m/', verbose_name='Datei')),
                ('hochgeladen_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hochgeladene_workflow_dokumente', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
                ('schritt_instanz', models.ForeignKey(blank=True, help_text='Optional: Zu welchem Schritt gehört das Dokument?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='workflows.workflowschrittinstanz', verbose_name='Schritt-Instanz')),
                ('workflow_instanz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='workflows.workflowinstanz', verbose_name='Workflow-Instanz')),
            ],
            options={
                'verbose_name': 'Workflow-Dokument',
                'verbose_name_plural': 'Workflow-Dokumente',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBewerber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('beworben', 'Hat sich beworben'), ('ausgewaehlt', 'Für Verfahren ausgewählt'), ('platz_1', '1. Platz (wird bestellt)'), ('platz_2', '2. Platz'), ('platz_3', '3. Platz'), ('abgelehnt', 'Abgelehnt')], default='beworben', max_length=20, verbose_name='Status')),
                ('ranking', models.IntegerField(blank=True, help_text='1 = Bester, 2 = Zweiter, 3 = Dritter', null=True, verbose_name='Ranking')),
                ('bewerbung_datei', models.FileField(blank=True, null=True, upload_to='bewerbungen/%Y/%m/', verbose_name='Bewerbungsunterlagen')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('anwaerter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bewerbungen', to='personen.notaranwaerter', verbose_name='Notar-Anwärter')),
                ('workflow_instanz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewerber', to='workflows.workflowinstanz', verbose_name='Workflow-Instanz')),
            ],
            options={
                'verbose_name': 'Workflow-Bewerber',
                'verbose_name_plural': 'Workflow-Bewerber',
                'ordering': ['ranking', 'anwaerter__nachname'],
                'unique_together': {('workflow_instanz', 'anwaerter')},
            },
        ),
    ]
