# Generated by Django 5.2.9 on 2025-12-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowdokument_workflowbewerber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowinstanz',
            name='aktenzeichen',
        ),
    ]
