# Generated by Django 5.2.9 on 2025-12-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowdokument_workflowbewerber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowdokument',
            name='hochgeladen_von',
        ),
        migrations.RemoveField(
            model_name='workflowdokument',
            name='schritt_instanz',
        ),
        migrations.RemoveField(
            model_name='workflowdokument',
            name='workflow_instanz',
        ),
        migrations.RemoveField(
            model_name='workflowkommentar',
            name='benutzer',
        ),
        migrations.RemoveField(
            model_name='workflowkommentar',
            name='schritt_instanz',
        ),
        migrations.RemoveField(
            model_name='workflowkommentar',
            name='workflow_instanz',
        ),
        migrations.AlterUniqueTogether(
            name='workflowschrittuebergang',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workflowschrittuebergang',
            name='von_schritt',
        ),
        migrations.RemoveField(
            model_name='workflowschrittuebergang',
            name='zu_schritt',
        ),
        migrations.DeleteModel(
            name='WorkflowBewerber',
        ),
        migrations.DeleteModel(
            name='WorkflowDokument',
        ),
        migrations.DeleteModel(
            name='WorkflowKommentar',
        ),
        migrations.DeleteModel(
            name='WorkflowSchrittUebergang',
        ),
    ]
