# Generated by Django 5.2.9 on 2025-12-19 11:01

from django.db import migrations, models


def convert_workflow_instanz_status(apps, schema_editor):
    """Konvertiert WorkflowInstanz Status zu neuen Werten."""
    WorkflowInstanz = apps.get_model('workflows', 'WorkflowInstanz')

    # 'entwurf' und 'aktiv' bleiben gleich
    # 'abgeschlossen' und 'abgebrochen' → 'archiviert'
    WorkflowInstanz.objects.filter(status='abgeschlossen').update(status='archiviert')
    WorkflowInstanz.objects.filter(status='abgebrochen').update(status='archiviert')


def convert_workflow_schritt_instanz_status(apps, schema_editor):
    """Konvertiert WorkflowSchrittInstanz Status zu neuen Werten."""
    WorkflowSchrittInstanz = apps.get_model('workflows', 'WorkflowSchrittInstanz')

    # 'ausstehend', 'in_bearbeitung', 'fehlgeschlagen' → 'pending'
    WorkflowSchrittInstanz.objects.filter(status='ausstehend').update(status='pending')
    WorkflowSchrittInstanz.objects.filter(status='in_bearbeitung').update(status='pending')
    WorkflowSchrittInstanz.objects.filter(status='fehlgeschlagen').update(status='pending')

    # 'abgeschlossen', 'uebersprungen' → 'completed'
    WorkflowSchrittInstanz.objects.filter(status='abgeschlossen').update(status='completed')
    WorkflowSchrittInstanz.objects.filter(status='uebersprungen').update(status='completed')


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_remove_unused_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowinstanz',
            name='abgeschlossen_am',
        ),
        migrations.RemoveField(
            model_name='workflowinstanz',
            name='faellig_am',
        ),
        migrations.RemoveField(
            model_name='workflowinstanz',
            name='gestartet_am',
        ),
        migrations.RemoveField(
            model_name='workflowschritt',
            name='geschaetzte_dauer_tage',
        ),
        migrations.RemoveField(
            model_name='workflowschritt',
            name='standard_zustaendige_rolle',
        ),
        migrations.RemoveField(
            model_name='workflowschrittinstanz',
            name='abgeschlossen_am',
        ),
        migrations.RemoveField(
            model_name='workflowschrittinstanz',
            name='faellig_am',
        ),
        migrations.RemoveField(
            model_name='workflowschrittinstanz',
            name='gestartet_am',
        ),
        migrations.RemoveField(
            model_name='workflowschrittinstanz',
            name='zugewiesen_an',
        ),
        migrations.RemoveField(
            model_name='workflowtyp',
            name='erfordert_sequentielle_abarbeitung',
        ),
        migrations.RemoveField(
            model_name='workflowtyp',
            name='erlaube_parallele_schritte',
        ),
        migrations.AddField(
            model_name='workflowinstanz',
            name='archiviert_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am'),
        ),
        # Konvertiere Status-Werte BEVOR die Choices geändert werden
        migrations.RunPython(convert_workflow_instanz_status, migrations.RunPython.noop),
        migrations.RunPython(convert_workflow_schritt_instanz_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workflowinstanz',
            name='status',
            field=models.CharField(choices=[('entwurf', 'Entwurf'), ('aktiv', 'Aktiv'), ('archiviert', 'Archiviert')], default='entwurf', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workflowschrittinstanz',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('completed', 'Abgeschlossen')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
