# Generated by Django 5.2.9 on 2025-12-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_simplify_workflow_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstanz',
            name='jahr',
            field=models.PositiveIntegerField(default=2025, help_text='Jahr für Kennungssystem', verbose_name='Jahr'),
        ),
        migrations.AddField(
            model_name='workflowinstanz',
            name='kennung',
            field=models.CharField(blank=True, help_text='Eindeutige Kennung (z.B. 2025-BES-001)', max_length=50, unique=True, verbose_name='Kennung'),
        ),
        migrations.AddField(
            model_name='workflowinstanz',
            name='laufende_nummer',
            field=models.PositiveIntegerField(default=0, help_text='Laufende Nummer innerhalb Jahr und Typ', verbose_name='Laufende Nummer'),
        ),
        migrations.AddField(
            model_name='workflowtyp',
            name='kuerzel',
            field=models.CharField(blank=True, help_text='Kürzel für Kennung (z.B. BES, BP, NOT)', max_length=10, null=True, unique=True, verbose_name='Kürzel'),
        ),
    ]
