# Generated by Django 5.2.9 on 2025-12-19 15:10

from django.db import migrations


def populate_workflow_typ_kuerzel(apps, schema_editor):
    """Setzt Kürzel für bestehende Workflow-Typen."""
    WorkflowTyp = apps.get_model('workflows', 'WorkflowTyp')

    # Bestellungsprozess → "BP"
    try:
        bestellung = WorkflowTyp.objects.get(name='Bestellungsprozess')
        bestellung.kuerzel = 'BP'
        bestellung.save()
    except WorkflowTyp.DoesNotExist:
        pass

    # Besetzungsverfahren → "BES"
    try:
        besetzung = WorkflowTyp.objects.get(name='Besetzungsverfahren')
        besetzung.kuerzel = 'BES'
        besetzung.save()
    except WorkflowTyp.DoesNotExist:
        pass


def reverse_workflow_typ_kuerzel(apps, schema_editor):
    """Entfernt Kürzel (für Rollback)."""
    WorkflowTyp = apps.get_model('workflows', 'WorkflowTyp')
    WorkflowTyp.objects.filter(kuerzel__in=['BP', 'BES']).update(kuerzel=None)


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflowinstanz_jahr_workflowinstanz_kennung_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_workflow_typ_kuerzel,
            reverse_workflow_typ_kuerzel
        ),
    ]
