# Generated by Django 5.2.9 on 2025-12-19 15:10

from django.db import migrations
from django.db.models import Max


def populate_workflow_instanz_kennung(apps, schema_editor):
    """Generiert Kennungen für bestehende Workflow-Instanzen."""
    WorkflowInstanz = apps.get_model('workflows', 'WorkflowInstanz')

    # Alle Workflows ohne Kennung
    workflows_ohne_kennung = WorkflowInstanz.objects.filter(kennung='')

    for workflow in workflows_ohne_kennung:
        # Kürzel vom Typ holen
        if not workflow.workflow_typ.kuerzel:
            # Falls kein Kürzel vorhanden: Überspringen (wird später manuell gesetzt)
            continue

        # Jahr vom erstellt_am Feld nehmen
        jahr = workflow.erstellt_am.year
        workflow.jahr = jahr

        kuerzel = workflow.workflow_typ.kuerzel

        # Höchste laufende Nummer für dieses Jahr + Typ ermitteln
        letzte_nummer = WorkflowInstanz.objects.filter(
            workflow_typ=workflow.workflow_typ,
            jahr=jahr
        ).exclude(
            id=workflow.id  # Aktuellen Workflow ausschließen
        ).aggregate(max_nummer=Max('laufende_nummer'))['max_nummer'] or 0

        # Neue Nummer generieren
        workflow.laufende_nummer = letzte_nummer + 1

        # Kennung zusammensetzen
        workflow.kennung = f"{jahr}-{kuerzel}-{workflow.laufende_nummer:03d}"

        workflow.save(update_fields=['kennung', 'jahr', 'laufende_nummer'])


def reverse_workflow_instanz_kennung(apps, schema_editor):
    """Entfernt Kennungen (für Rollback)."""
    WorkflowInstanz = apps.get_model('workflows', 'WorkflowInstanz')
    WorkflowInstanz.objects.all().update(kennung='', jahr=2025, laufende_nummer=0)


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_populate_workflow_typ_kuerzel'),
    ]

    operations = [
        migrations.RunPython(
            populate_workflow_instanz_kennung,
            reverse_workflow_instanz_kennung
        ),
    ]
