# Generated by Django 5.2.9 on 2025-12-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0001_initial'),
        ('services', '0001_initial'),
        ('workflows', '0008_populate_workflow_instanz_kennung'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstanz',
            name='bewerber',
            field=models.ManyToManyField(blank=True, help_text='Anwärter die sich um die Stelle bewerben', related_name='workflows_als_bewerber', to='personen.notaranwaerter', verbose_name='Bewerber'),
        ),
        migrations.AddField(
            model_name='workflowinstanz',
            name='referenten',
            field=models.ManyToManyField(blank=True, help_text='Notare die als Referenten am Workflow beteiligt sind', related_name='workflows_als_referent', to='personen.notar', verbose_name='Referenten'),
        ),
        migrations.AddField(
            model_name='workflowschritt',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service der bei diesem Schritt angeboten wird', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_schritte', to='services.servicedefinition', verbose_name='Verknüpfter Service'),
        ),
    ]
