# Generated by Django 5.2.9 on 2025-12-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0003_alter_notar_notar_id_and_more'),
        ('workflows', '0009_workflowinstanz_bewerber_workflowinstanz_referenten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstanz',
            name='betroffene_person',
            field=models.ForeignKey(blank=True, help_text='Notariatskandidat, der betroffen ist (z.B. bei Bestellungsprozess)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='personen.notaranwaerter', verbose_name='Betroffene Person'),
        ),
        migrations.AlterField(
            model_name='workflowinstanz',
            name='bewerber',
            field=models.ManyToManyField(blank=True, help_text='Kandidat die sich um die Stelle bewerben', related_name='workflows_als_bewerber', to='personen.notaranwaerter', verbose_name='Bewerber'),
        ),
    ]
