# Generated by Django 5.2.9 on 2025-12-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0003_alter_notar_notar_id_and_more'),
        ('workflows', '0010_alter_workflowinstanz_betroffene_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowinstanz',
            name='betroffene_person',
        ),
        migrations.AddField(
            model_name='workflowinstanz',
            name='betroffene_kandidaten',
            field=models.ManyToManyField(blank=True, help_text='Notariatskandidaten, die von diesem Workflow betroffen sind', related_name='workflows_als_betroffener', to='personen.notaranwaerter', verbose_name='Betroffene Kandidaten'),
        ),
        migrations.AddField(
            model_name='workflowinstanz',
            name='betroffene_notare',
            field=models.ManyToManyField(blank=True, help_text='Notare, die von diesem Workflow betroffen sind', related_name='workflows_als_betroffener', to='personen.notar', verbose_name='Betroffene Notare'),
        ),
    ]
