# Generated by Django 5.2.9 on 2025-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_remove_workflowinstanz_betroffene_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstanz',
            name='fertigstellungsdatum',
            field=models.DateField(blank=True, help_text='Geplantes Datum zur Fertigstellung des Workflows', null=True, verbose_name='Fertigstellungsdatum'),
        ),
    ]
