# Generated by Django 5.2.9 on 2025-12-21 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_gesendeteemail_anwaerter'),
        ('workflows', '0012_workflowinstanz_fertigstellungsdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowschritt',
            name='email_vorlage',
            field=models.ForeignKey(blank=True, help_text='E-Mail-Vorlage die in diesem Schritt verwendet wird', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_schritte', to='emails.emailvorlage', verbose_name='E-Mail-Vorlage'),
        ),
    ]
