# Generated by Django 5.2.9 on 2025-12-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_workflowschritt_email_vorlage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstanz',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Aktiv'), ('archiviert', 'Archiviert')], default='aktiv', max_length=20, verbose_name='Status'),
        ),
    ]
