# Generated by Django 5.2.9 on 2025-12-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benutzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kammerbenutzer',
            name='profilbild',
            field=models.ImageField(blank=True, help_text='Profilbild des Benutzers', null=True, upload_to='profilbilder/', verbose_name='Profilbild'),
        ),
    ]
