# Generated by Django 5.2.9 on 2025-12-18 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. "Anfrage Strafregisterauszug"', max_length=200, verbose_name='Name der Vorlage')),
                ('kategorie', models.CharField(choices=[('strafregister', 'Strafregisterauszug'), ('bestellung', 'Bestellungsverfahren'), ('zulassung', 'Zulassungsverfahren'), ('aufsicht', 'Aufsichtsangelegenheiten'), ('allgemein', 'Allgemein'), ('sonstiges', 'Sonstiges')], default='allgemein', max_length=50, verbose_name='Kategorie')),
                ('betreff', models.CharField(max_length=200, verbose_name='E-Mail-Betreff')),
                ('nachricht', models.TextField(help_text='Platzhalter: {vorname}, {nachname}, {titel}, {notar_id}, {anwaerter_id}, {notarstelle}', verbose_name='E-Mail-Text')),
                ('standard_empfaenger', models.EmailField(help_text='Standard-E-Mail-Adresse, an die diese Vorlage gesendet wird', max_length=254, verbose_name='Standard-Empfänger')),
                ('cc_empfaenger', models.CharField(blank=True, help_text='Mehrere E-Mail-Adressen mit Komma trennen', max_length=500, verbose_name='CC-Empfänger')),
                ('ist_aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail-Vorlage',
                'verbose_name_plural': 'E-Mail-Vorlagen',
                'ordering': ['kategorie', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GesendeteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empfaenger', models.EmailField(max_length=254, verbose_name='Empfänger')),
                ('cc_empfaenger', models.CharField(blank=True, max_length=500, verbose_name='CC-Empfänger')),
                ('betreff', models.CharField(max_length=200, verbose_name='Betreff')),
                ('nachricht', models.TextField(verbose_name='Nachricht')),
                ('erfolgreich', models.BooleanField(default=True, verbose_name='Erfolgreich gesendet')),
                ('fehler', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('gesendet_am', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('anwaerter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gesendete_emails', to='personen.notaranwaerter', verbose_name='Anwärter')),
                ('gesendet_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gesendet von')),
                ('notar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gesendete_emails', to='personen.notar', verbose_name='Notar')),
                ('vorlage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailvorlage', verbose_name='Verwendete Vorlage')),
            ],
            options={
                'verbose_name': 'Gesendete E-Mail',
                'verbose_name_plural': 'Gesendete E-Mails',
                'ordering': ['-gesendet_am'],
            },
        ),
    ]
