# Generated by Django 5.2.9 on 2025-12-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('workflows', '0008_populate_workflow_instanz_kennung'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvorlage',
            name='workflow_typ',
            field=models.ForeignKey(blank=True, help_text='Zuordnung zu einem Workflow (leer = Allgemeine Vorlage)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_vorlagen', to='workflows.workflowtyp', verbose_name='Workflow-Typ'),
        ),
    ]
