# Generated by Django 5.2.9 on 2025-12-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailvorlage_workflow_typ'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvorlage',
            name='standard_anhaenge',
            field=models.ManyToManyField(blank=True, help_text='Dokumente die standardmäßig angehängt werden', related_name='email_vorlagen', to='services.dokument', verbose_name='Standard-Anhänge'),
        ),
        migrations.AddField(
            model_name='gesendeteemail',
            name='anhaenge',
            field=models.ManyToManyField(blank=True, related_name='versendungen', to='services.dokument', verbose_name='Anhänge'),
        ),
        migrations.AddField(
            model_name='gesendeteemail',
            name='service_ausfuehrung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gesendete_emails', to='services.serviceausfuehrung', verbose_name='Service-Ausführung'),
        ),
    ]
