# Generated by Django 5.2.9 on 2025-12-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailvorlage_standard_anhaenge_and_more'),
        ('personen', '0003_alter_notar_notar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesendeteemail',
            name='anwaerter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gesendete_emails', to='personen.notaranwaerter', verbose_name='Kandidat'),
        ),
    ]
